version: '2.2'
services:
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  kibana:
    container_name: kib01
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - elasticsearch.hosts=http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic


networks:
  elastic:
    driver: bridge